parameters:
    default_cdn_strategy: "id"
    APP_URL: "%env(string:default:default_whitespace:APP_URL)%"

shopware:
    filesystem:
        private:
            type: "local"
            config:
                root: "%kernel.project_dir%/files"
        public:
            type: "local"
            config:
                root: "%kernel.project_dir%/public"
        temp:
            type: "local"
            config:
                root: "%kernel.project_dir%/var"
        theme:
        asset:
        sitemap:
        allowed_extensions: ["jpg", "jpeg", "png", "webp", "gif", "svg", "bmp", "tiff", "tif", "eps", "webm", "mkv", "flv", "ogv", "ogg", "mov", "mp4", "avi", "wmv", "pdf", "aac", "mp3", "wav", "flac", "oga", "wma", "txt", "doc", "ico"]

    cdn:
        url: ''
        strategy: "%env(string:default:default_cdn_strategy:SHOPWARE_CDN_STRATEGY_DEFAULT)%"

    api:
        max_limit: 500
        api_browser:
            auth_required: true
        store:
            context_lifetime: 'P1D' # 1 day interval, see also https://www.php.net/manual/en/dateinterval.construct.php#refsect1-dateinterval.construct-parameters
    admin_worker:
        enable_admin_worker: true
        # This has to be lower than PHP's max_execution_time (default: 30s)
        poll_interval: 20
        transports: ["default"]

    auto_update:
        enabled: true

    store:
        frw: false

    sitemap:
        batchsize: 100
        custom_urls:
        excluded_urls:

    deployment:
        blue_green: '%env(bool:default:defaults_bool_true:BLUE_GREEN_DEPLOYMENT)%'

    media:
        enable_url_upload_feature: true
        enable_url_validation: true

    feature:
        flags:
            - name: FEATURE_NEXT_1797
              default: false
              major: true
              description: "composer require for plugins"
            - name: FEATURE_NEXT_11917
              major: false
              description: "dynamic plugin acl privileges"
            - name: FEATURE_NEXT_10552
              default: false
              major: true
              description: "custom search index and ranking"
              # issue: NEXT-13539
            - name: FEATURE_NEXT_12608
              default: false
              major: true
              description: "App System Store"
            # issue: NEXT-13469
            - name: FEATURE_NEXT_10514
              default: false
              major: false
            - name: FEATURE_NEXT_12429
              default: false
              major: true
              description: "Improve product UX"
              # issue: NEXT-13759
            - name: FEATURE_NEXT_13810
              default: false
              major: true
              description: "Deprecate old promotion module"
              # issue: NEXT-13810
            - name: FEATURE_NEXT_6544
              default: false
              major: false
              description: "Image assignment for variants"
              # issue: NEXT-6544
            - name: FEATURE_NEXT_14114
              default: false
              major: false
              description: "Brexit Changes"
              # issue: NEXT-14114
            - name: FEATURE_NEXT_12455
              default: false
              major: false
              description: "Captcha Integration"
              # issue: NEXT-12455

    logger:
        file_rotation_count: 14

    cache:
        invalidation:
            delay: 0
            http_cache: ['logged-in', 'cart-filled']
            product_listing_route: []
            product_detail_route: []
            product_search_route: [ ]
            product_suggest_route: [ ]
            payment_method_route: []
            shipping_method_route: []
            navigation_route: []
            language_route: []
            currency_route: []
