parameters:
    default_cdn_strategy: "id"
    APP_URL: "%env(string:default:default_whitespace:APP_URL)%"

shopware:
    filesystem:
        private:
            type: "local"
            config:
                root: "%kernel.project_dir%/files"
        public:
            type: "local"
            config:
                root: "%kernel.project_dir%/public"
        temp:
            type: "local"
            config:
                root: "%kernel.project_dir%/var"
        theme:
        asset:
        sitemap:
        allowed_extensions: ["jpg", "jpeg", "png", "webp", "gif", "svg", "bmp", "tiff", "tif", "eps", "webm", "mkv", "flv", "ogv", "ogg", "mov", "mp4", "avi", "wmv", "pdf", "aac", "mp3", "wav", "flac", "oga", "wma", "txt", "doc", "ico"]

    cdn:
        url: ''
        strategy: "%env(string:default:default_cdn_strategy:SHOPWARE_CDN_STRATEGY_DEFAULT)%"

    api:
        max_limit: 500
        api_browser:
            auth_required: true

    admin_worker:
        enable_admin_worker: true
        poll_interval: 30
        transports: ["default"]

    auto_update:
        enabled: true

    store:
        frw: false

    sitemap:
        batchsize: 100
        custom_urls:
        excluded_urls:

    deployment:
        blue_green: '%env(bool:default:defaults_bool_true:BLUE_GREEN_DEPLOYMENT)%'

    media:
        enable_url_upload_feature: true
        enable_url_validation: true

    feature:
        flags:
            - name: FEATURE_NEXT_1797
              default: false
              major: true
              description: "composer require for plugins"
            - name: FEATURE_NEXT_7453
              major: true
              description: "use custom name prefix for nested routes"
            - name: FEATURE_NEXT_8172
              major: true
              description: "prevent plugins to extend the first level menu entries"
            - name: FEATURE_NEXT_12009
              major: true
              description: "remove countries from sales channel object inside context"
            - name: FEATURE_NEXT_10549
              major: false
              description: "save cart or products on wishlist"
            - name: FEATURE_NEXT_10078
              major: false
              description: "cms product page layouts"
            - name: FEATURE_NEXT_10539
              major: false
              description: "prevent deletion of used rules"
            - name: FEATURE_NEXT_12092
              default: false
              major: true
              description: "correct spelling of a config key"
            - name: FEATURE_NEXT_11253
              default: false
              major: true
              description: "reduce request payload of cms listing"
            - name: FEATURE_NEXT_10550
              default: false
              major: false
              description: "add rich-text editor with variables"
            - name: FEATURE_NEXT_12016
              default: false
              major: false
              description: "improve promotions UX"
            - name: FEATURE_NEXT_11917
              major: false
              description: "dynamic plugin acl privileges"
            - name: FEATURE_NEXT_10553
              default: false
              major: false
              description: "From prices for variant products"
            - name: FEATURE_NEXT_12108
              default: false
              major: true
              description: "show property group in rule builder and dpg"
            - name: FEATURE_NEXT_10552
              default: false
              major: true
              description: "custom search index and ranking"
            - name: FEATURE_NEXT_12553
              default: false
              major: true
              description: "Improve template hierarchy resolving"
            - name: FEATURE_NEXT_12608
              default: false
              major: true
              description: "App System Store"
            - name: FEATURE_NEXT_7365
              default: false
              major: true
              description: "single SCSS entry file for plugins"
            - name: FEATURE_NEXT_12289
              default: false
              major: true
              description: "Rule detail page assignments tab"
            - name: FEATURE_NEXT_12032
              default: false
              major: true
              description: "Add landing pages"
            - name: FEATURE_NEXT_12246
              default: false
              major: true
              description: "Exchange standard mailer SwiftMailer to Symfony/Mailer"
            - name: FEATURE_NEXT_12942
              default: false
              major: true
              description: "Add maximum width for logo"
            - name: FEATURE_NEXT_12957
              default: false
              major: true
              description: "Separate plugin download and update action"
            - name: FEATURE_NEXT_9831
              default: false
              major: false
              description: "Filters & Search for Admin Grids"
            - name: FEATURE_NEXT_12429
              default: false
              major: true
              description: "Improve product UX"

    logger:
        file_rotation_count: 14
