storefront:
    csrf:
        enabled: true
        mode: twig
    htmlPurifier:
        cacheDir: '%kernel.cache_dir%'
        cacheEnabled: true

    reverse_proxy:
        enabled: false
        ban_method: "BAN" # This can defer from used reverse proxy
        hosts: [ "http://varnish" ]
        max_parallel_invalidations: 2
        redis_url: "redis://redis"
